version: 2
jobs:
  build:
    docker:
      - image: boostorg/boost_regression_docker
    parallelism: 2
    steps:
      - checkout
      - run:
          no_output_timeout: 20m
          command: source ./ci_build_results_all.sh
